name: project_getCodeConfigSave_2

authors:
  - Asiya Shaji

type: SUITE

init:
 - create_project_abstract

endpoint: /projects/{{@create_project_abstract_Response.data.id}}/autocodeconfig

method: GET

auth: Default

headers:
- 'Content-Type: application/json'


assertions:
  - "@StatusCode == 200"
  - "@Response.errors == false"
  - "@Response.data != EMPTY"

cleanup:
- delete_project_abstract
 #- delete_GitHubacc_abstract

severity: Major

category: Functional

tags:
- V2
