name: env_findby_Rating

authors:
  - Asiya Shaji

type: SUITE

init:
   - create_GitHubacc_abstract
   - create_project_GitHub_abstract
   - create_environment_abstract
   - job_findby_projectid_abstract

endpoint: /envs/{{@create_environment_abstract_Response.data.id}}/envrating

method: GET

auth: Default

assertions:
  - "@StatusCode == 200"
  - "@Response.errors == false"
  - "@Response.data != EMPTY"

cleanup:
    - delete_job_findby_projectid_abstract
    - delete_environment_abstract
    - delete_project_GitHub_abstract
    - delete_GitHubacc_abstract

severity: Major

category: Functional

tags:
    - V2

policies:
    logger: DEBUG
